name: SCANPLOT
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex
#  - _openmp_mutex
  - attrs
  - backcall
  - blas
  - bleach
  - boost-cpp
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - cartopy
  - certifi
  - cffi
  - cfitsio
  - chardet
  - cryptography
  - curl
  - cycler
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - fontconfig
  - freetype
  - freexl
  - gdal
  - geos
  - geotiff
  - gettext
  - gh
  - giflib
  - glib
  - gst-plugins-base
  - gstreamer
  - hdf4
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - json-c
  - jsonschema
  - jupyter_client
  - jupyter_core
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - libclang
  - libcurl
  - libdap4
  - libedit
  - libev
  - libffi
#  - libgcc-ng
  - libgdal
  - libgfortran-ng
#  - libgomp
  - libiconv
  - libkml
  - libllvm9
  - libnetcdf
  - libnghttp2
  - libpng
  - libpq
  - libsodium
  - libspatialite
  - libssh2
#  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
#  - libxkbcommon
  - libxml2
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - nspr
  - nss
  - numpy
  - numpy-base
  - olefile
  - openjpeg
  - openssl
  - owslib
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prometheus_client
  - prompt-toolkit
  - pthread-stubs
  - ptyprocess
  - pycparser
  - pyepsg
  - pygments
  - pykdtree
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyrsistent
  - pyshp
  - pysocks
  - python=3.8.2
  - python-dateutil
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - readline
  - requests
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - shapely
  - six
  - sqlite
  - tbb
  - terminado
  - testpath
  - tiledb
  - tk
  - tornado
  - traitlets
  - tzcode
  - urllib3
  - wcwidth
  - webencodings
  - wget
  - wheel
  - widgetsnbextension
  - xarray
  - xerces-c
  - xlsxwriter
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - mkdocs
  - pip:
#    - pyqt5-sip
#    - pyqtchart
#    - pyqtwebengine
    - skillmetrics
    - mkdocs-material
    - mkdocs-video
    - mkdocs-pdf-export-plugin
    - mkdocs-jupyter
prefix: /home/carlos/anaconda3/envs/SCANPLOT
